export const FRAUD_WEIGHTS = {
    FAILED_LOGIN_BURST: 35,
    LOGIN_RATE_LIMIT: 20,
    PAYMENT_FAILURE_BURST: 20,
    DUPLICATE_PAYMENT: 25,
    RAPID_PAYMENT_ATTEMPTS: 15,
    SUSPICIOUS_BIDDING: 15,
    MESSAGE_SPAM: 15,
    AI_ABUSE: 10,
    RAPID_WITHDRAWALS: 20,
    UNUSUAL_WITHDRAWAL: 20
};

export const RISK_THRESHOLDS = {
    LOW_MAX: 29,
    MEDIUM_MAX: 59,
    HIGH_MAX: 79
};

export const FRAUD_LIMITS = {
    FAILED_LOGIN_LIMIT: 5,
    FAILED_LOGIN_WINDOW_MINS: 15,
    PAYMENT_FAILURE_LIMIT: 3,
    PAYMENT_FAILURE_WINDOW_MINS: 10,
    BIDDING_LIMIT: 5,
    BIDDING_WINDOW_MINS: 5,
    MESSAGE_LIMIT: 10,
    MESSAGE_WINDOW_MINS: 2,
    AI_ABUSE_LIMIT: 5,
    AI_ABUSE_WINDOW_MINS: 10,
    WITHDRAWAL_LIMIT: 3,
    WITHDRAWAL_WINDOW_MINS: 30,
    COOLDOWN_WINDOW_MINS: 5
};
